// components/BgImage.vue
<template>
    <div id="component" :style="'background-image: url(' + image + ');'" />
</template>

<script>
/**
 * BgImage.vue
 * @description Display an image using background-image instead of <img/>
 */
export default {
    name: 'BgImage',
    props: {
        image: {
            type: String,
            required: true,
        },
    },
}
</script>

<style>
#component {
    background-size: cover;
    background-position: center;
    height: 100%;
    width: 100%;
}
</style>

// src/components/BgImage.svelte
<!--
  @component

  ## BgImage
  Display an image using `background-image` instead of `<img/>`

  @param image - the URL to the image
-->

<script lang="ts">
    export let image: string
    const style = 'background-image: url(' + image + ');'
</script>

<div class="bgimage" style={style} />

<style>
.bgimage {
    background-size: cover;
    background-position: center;
    height: 100%;
    width: 100%;
}
</style>
